# Youtube Trending Videos EDA

#### Importing Libraries

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

#### Loading the Dataset

In [7]:
df = pd.read_csv('youtube.csv')

#### Displaying the first 10 rows of the dataset to get a quick look at the dataset

In [8]:
df.head(10)

,index,video_id,trending_date,title,channel_title,category_id,publish_date,time_frame,published_day_of_week,publish_country,tags,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed
0,0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,13/11/2017,17:00 to 17:59,Monday,US,SHANtell martin,748374,57527,2966,15954,False,False,False
1,1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,13/11/2017,7:00 to 7:59,Monday,US,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,False,False,False
2,2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,12/11/2017,19:00 to 19:59,Sunday,US,"racist superman|""rudy""""|""""mancuso""""|""""king""""|""...",3191434,146033,5339,8181,False,False,False
3,3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,13/11/2017,11:00 to 11:59,Monday,US,"rhett and link|""gmm""""|""""good mythical morning""...",343168,10172,666,2146,False,False,False
4,4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,12/11/2017,18:00 to 18:59,Sunday,US,"ryan|""higa""""|""""higatv""""|""""nigahiga""""|""""i dare ...",2095731,132235,1989,17518,False,False,False
5,5,gHZ1Qz0KiKM,17.14.11,2 Weeks with iPhone X,iJustine,28,13/11/2017,19:00 to 19:59,Monday,US,"ijustine|""week with iPhone X""""|""""iphone x""""|""""...",119180,9763,511,1434,False,False,False
6,6,39idVpFF7NQ,17.14.11,Roy Moore & Jeff Sessions Cold Open - SNL,Saturday Night Live,24,12/11/2017,5:00 to 5:59,Sunday,US,"SNL|""Saturday Night Live""""|""""SNL Season 43""""|""...",2103417,15993,2445,1970,False,False,False
7,7,nc99ccSXST0,17.14.11,5 Ice Cream Gadgets put to the Test,CrazyRussianHacker,28,12/11/2017,21:00 to 21:59,Sunday,US,"5 Ice Cream Gadgets|""Ice Cream""""|""""Cream Sandw...",817732,23663,778,3432,False,False,False
8,8,jr9QtXwC9vc,17.14.11,The Greatest Showman | Official Trailer 2 [HD]...,20th Century Fox,1,13/11/2017,14:00 to 14:59,Monday,US,"Trailer|""Hugh Jackman""""|""""Michelle Williams""""|...",826059,3543,119,340,False,False,False
9,9,TUmyygCMMGA,17.14.11,Why the rise of the robots wonâ€™t mean the en...,Vox,25,13/11/2017,13:00 to 13:59,Monday,US,"vox.com|""vox""""|""""explain""""|""""shift change""""|""""...",256426,12654,1363,2368,False,False,False

#### Displaying the total number of rows and columns in the dataset

In [9]:
rows, columns = df.shape
print(f"This dataset contains {rows} rows and {columns} Columns")

This dataset contains 161470 rows and 18 Columns

#### Displaying the columns names

In [11]:
print(df.columns)

Index(['index', 'video_id', 'trending_date', 'title', 'channel_title',
       'category_id', 'publish_date', 'time_frame', 'published_day_of_week',
       'publish_country', 'tags', 'views', 'likes', 'dislikes',
       'comment_count', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed'],
      dtype='str')

#### Based on the publicly available Youtube metadata, the meaning of each column in the dataset is as follows:

- index: Row index of the dataset. (Numeric)
- video_id: Unique identifier of the YouTube video. (Text)
- trending_date: The date when the video became trending on YouTube. (Date)
- title: The title of the video. (Text)
- channel_title: The title of the YouTube channel that published the video. (Text)
- category_id: The category ID assigned to the video by YouTube. (Numeric)
- publish_date: The date when the video was published on YouTube. (Date)
- time_frame: The duration of time the video has been trending on YouTube. (Text)
- published_day_of_week: The day of the week when the video was published. (Text)
- publish_country: The country where the video was published. (Text)
- tags: The tags or keywords associated with the video. (Text)
- views: The number of views a video has received. (Numeric)
- likes: The number of likes a video has received. (Numeric)
- dislikes: The number of dislikes a video has received. (Numeric)
- comment_count: The number of comments a video has received. (Numeric)
- comments_disabled: Indicates whether comments are disabled for the video. (Boolean)
- ratings_disabled: Indicates whether ratings are disabled for the video. (Boolean)
- video_error_or_removed: Indicates whether the video is unavailable, removed, or has an error. (Boolean)

In [12]:
df.describe()

,index,category_id,views,likes,dislikes,comment_count
count,161470.00000,161470.000000,1.614700e+05,1.614700e+05,1.614700e+05,1.614700e+05
mean,80734.50000,19.461151,2.419854e+06,6.566194e+04,3.490153e+03,7.035494e+03
std,46612.51832,7.432001,1.043749e+07,2.260617e+05,3.114779e+04,3.404121e+04
min,0.00000,1.000000,2.230000e+02,0.000000e+00,0.000000e+00,0.000000e+00
25%,40367.25000,15.000000,1.015382e+05,1.975000e+03,8.500000e+01,2.790000e+02
50%,80734.50000,23.000000,3.847395e+05,9.840000e+03,3.480000e+02,1.144000e+03
75%,121101.75000,24.000000,1.339528e+06,4.006275e+04,1.350000e+03,4.144750e+03
max,161469.00000,44.000000,4.245389e+08,5.613827e+06,1.944971e+06,1.626501e+06

#### Displaying the columns along with their data types

In [13]:
print(df.dtypes)

index                     int64
video_id                    str
trending_date               str
title                       str
channel_title               str
category_id               int64
publish_date                str
time_frame                  str
published_day_of_week       str
publish_country             str
tags                        str
views                     int64
likes                     int64
dislikes                  int64
comment_count             int64
comments_disabled          bool
ratings_disabled           bool
video_error_or_removed     bool
dtype: object

#### Obersvations on Data Types Clearly Some columns in the dataset are **not in the proper data type** for analysis.

- trending_date is stored as str but should be datetime.
- publish_date is stored as str but should be datetime.

These columns will need **cleaning and type conversion** before the analysis.

#### Checking all the unique values of each of the column

In [16]:
for col in df.columns:
    unique_vals = df[col].unique()
    print(f"Column Name : {col}")
    print(f"Number of unique values : {len(unique_vals)}")
    print(f"All unique values : {unique_vals}")
    print('-'*50)

Column Name : index
Number of unique values : 161470
All unique values : [     0      1      2 ... 161467 161468 161469]
--------------------------------------------------
Column Name : video_id
Number of unique values : 55886
All unique values : <StringArray>
['2kyS6SvSYSE', '1ZAPwfrtAFY', '5qpjK5DgCt4', 'puqaWrEC7tY', 'd380meD0W0M',
 'gHZ1Qz0KiKM', '39idVpFF7NQ', 'nc99ccSXST0', 'jr9QtXwC9vc', 'TUmyygCMMGA',
 ...
 'VI4NZW8q6nU', 'Tmv5f02jA5U', 'xxbkfmYFxnw', 'sbxP1ndw2ds', 'FoOi-oTaIEU',
 '7E1np354AEc', 'sGolxsMSGfQ', '8HNuRNi8t70', 'lbMKLzQ4cNQ', 'POTgw38-m58']
Length: 55886, dtype: str
--------------------------------------------------
Column Name : trending_date
Number of unique values : 205
All unique values : <StringArray>
['17.14.11', '17.15.11', '17.16.11', '17.17.11', '17.18.11', '17.19.11',
 '17.20.11', '17.21.11', '17.22.11', '17.23.11',
 ...
 '18.05.06', '18.06.06', '18.07.06', '18.08.06', '18.09.06', '18.10.06',
 '18.11.06', '18.12.06', '18.13.06', '18.14.06']
Length: 205, dtype: str
--------------------------------------------------
Column Name : title
Number of unique values : 56905
All unique values : <StringArray>
[                                                           'WE WANT TO TALK ABOUT OUR MARRIAGE',
                                'The Trump Presidency: Last Week Tonight with John Oliver (HBO)',
                                         'Racist Superman | Rudy Mancuso, King Bach & Lele Pons',
                                                              'Nickelback Lyrics: Real or Fake?',
                                                                      'I Dare You: GOING BALD!?',
                                                                         '2 Weeks with iPhone X',
                                                     'Roy Moore & Jeff Sessions Cold Open - SNL',
                                                           '5 Ice Cream Gadgets put to the Test',
                             'The Greatest Showman | Official Trailer 2 [HD] | 20th Century FOX',
                                       'Why the rise of the robots wonâ€™t mean the end of work',
 ...
                                                                             'TactiCOOL RELOADS',
                                               'What Koreans Think of BTS NOW? [2018 ver.] ðŸ’œ',
 'Hawaii volcano update: INCREDIBLE aerial pictures (USGS) show magnitude of Kilauea lava flows',
                        'Eid Makeup Look: Heavy Glam with Bronze Eyeshadow + 2 Lipstick Options',
                                                                    'Ultimate Safari Adventure!',
                       'Ð’ÐµÑ‡ÐµÑ€ Ñ Ð’Ð»Ð°Ð´Ð¸Ð¼Ð¸Ñ€Ð¾Ð¼ Ð¡Ð¾Ð»Ð¾Ð²ÑŒÐµÐ²Ñ‹Ð¼ Ð¾Ñ‚ 13.06.2018',
                                                                  'HOW2: How to Solve a Mystery',
                                                              'Eli Lik Lik Episode 13 Partie 01',
                                                              'Trump Advisor Grovels To Trudeau',
                  'ã€å®Œæ•´ç‰ˆã€‘é‡åˆ°ææ€–æƒ…äººè©²æ€Žéº¼è¾¦ï¼Ÿ2018.06.13å°æ˜Žæ˜Ÿå¤§è·Ÿç­']
Length: 56905, dtype: str
--------------------------------------------------
Column Name : channel_title
Number of unique values : 12361
All unique values : <StringArray>
[                 'CaseyNeistat',               'LastWeekTonight',
                  'Rudy Mancuso',         'Good Mythical Morning',
                      'nigahiga',                      'iJustine',
           'Saturday Night Live',            'CrazyRussianHacker',
              '20th Century Fox',                           'Vox',
 ...
                'Kaushal Beauty',                 'BallerVisions',
                        'NocutV', 'All things Hatala/FAN ACCOUNT',
                           'XXL',                'ZaidAliT Vlogs',
           'The Charisma Matrix',                 'ItsMyRayeRaye',
                      'Wolfychu',               'SevenSuperGirls']
Length: 12361, dtype: str
--------------------------------------------------
Column Name : category_id
Number of unique values : 18
All unique values : [22 24 23 28  1 25 17 10 15 27 26  2 19 20 29 43 30 44]
--------------------------------------------------
Column Name : publish_date
Number of unique values : 471
All unique values : <StringArray>
['13/11/2017', '12/11/2017', '29/05/2011', '06/11/2017', '10/11/2017',
 '21/04/2017', '11/11/2017', '09/11/2017', '17/10/2017', '08/11/2017',
 ...
 '24/11/2016', '22/09/2017', '31/07/2013', '13/01/2008', '31/12/2012',
 '12/10/2016', '31/10/2015', '26/09/2017', '09/10/2017', '27/07/2015']
Length: 471, dtype: str
--------------------------------------------------
Column Name : time_frame
Number of unique values : 24
All unique values : <StringArray>
['17:00 to 17:59',   '7:00 to 7:59', '19:00 to 19:59', '11:00 to 11:59',
 '18:00 to 18:59',   '5:00 to 5:59', '21:00 to 21:59', '14:00 to 14:59',
 '13:00 to 13:59',   '2:00 to 2:59',   '3:00 to 3:59', '20:00 to 20:59',
 '16:00 to 16:59', '15:00 to 15:59', '22:00 to 22:59', '12:00 to 12:59',
   '1:00 to 1:59', '23:00 to 23:59',   '6:00 to 6:59',   '0:00 to 0:59',
   '9:00 to 9:59',   '8:00 to 8:59',   '4:00 to 4:59', '10:00 to 10:59']
Length: 24, dtype: str
--------------------------------------------------
Column Name : published_day_of_week
Number of unique values : 7
All unique values : <StringArray>
['Monday', 'Sunday', 'Friday', 'Saturday', 'Thursday', 'Tuesday', 'Wednesday']
Length: 7, dtype: str
--------------------------------------------------
Column Name : publish_country
Number of unique values : 4
All unique values : <StringArray>
['US', 'GB', 'FRANCE', 'CANADA']
Length: 4, dtype: str
--------------------------------------------------
Column Name : tags
Number of unique values : 50239
All unique values : <StringArray>
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'SHANtell martin',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'last week tonight trump presidency|"last week tonight donald trump""|""john oliver trump""|""donald trump"""',
                                                                                                                                                                                                                                                         'racist superman|"rudy""|""mancuso""|""king""|""bach""|""racist""|""superman""|""love""|""rudy mancuso poo bear black white official music video""|""iphone x by pineapple""|""lelepons""|""hannahstocking""|""rudymancuso""|""inanna""|""anwar""|""sarkis""|""shots""|""shotsstudios""|""alesso""|""anitta""|""brazil""|""Getting My Driver's License | Lele Pons"""',
                                                                            'rhett and link|"gmm""|""good mythical morning""|""rhett and link good mythical morning""|""good mythical morning rhett and link""|""mythical morning""|""Season 12""|""nickelback lyrics""|""nickelback lyrics real or fake""|""nickelback""|""nickelback songs""|""nickelback song""|""rhett link nickelback""|""gmm nickelback""|""lyrics (website category)""|""nickelback (musical group)""|""rock""|""music""|""lyrics""|""chad kroeger""|""canada""|""music (industry)""|""mythical""|""gmm challenge""|""comedy""|""funny""|""challenge"""',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           'ryan|"higa""|""higatv""|""nigahiga""|""i dare you""|""idy""|""rhpc""|""dares""|""no truth""|""comments""|""comedy""|""funny""|""stupid""|""fail"""',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'ijustine|"week with iPhone X""|""iphone x""|""apple""|""iphone""|""iphone x review""|""iphone x unboxing"""',
 'SNL|"Saturday Night Live""|""SNL Season 43""|""Episode 1730""|""Tiffany Haddish""|""Roy Moore""|""Mikey Day""|""Mike Pence""|""Beck Bennett""|""Jeff Sessions""|""Kate McKinnon""|""s43""|""s43e5""|""episode 5""|""live""|""new york""|""comedy""|""sketch""|""funny""|""hilarious""|""late night""|""host""|""music""|""guest""|""laugh""|""impersonation""|""actor""|""improv""|""musician""|""comedian""|""actress""|""If Loving You Is Wrong""|""Oprah Winfrey""|""OWN""|""Girls Trip""|""The Carmichael Show""|""Keanu""|""Taylor Swift""|""Reputation""|""Look What You Made Me Do""|""ready for it?""|""cold open"""',
                                                                                                                                                                                                                                                                                                                                                      '5 Ice Cream Gadgets|"Ice Cream""|""Cream Sandwich Maker""|""gadgets""|""gadget review""|""review""|""unboxing""|""kitchen gadgets""|""Gadgets put to the Test""|""testing""|""10 Kitchen Gadgets""|""7 Camping Coffee Gadgets""|""10 Kitchen Gadgets put to the Test"""',
                                                                       'Trailer|"Hugh Jackman""|""Michelle Williams""|""Zac Efron""|""Zendaya""|""Rebecca Ferguson""|""pasek and paul""|""la la land""|""moulin rouge""|""high school musical""|""hugh jackman musical""|""zac efron musical""|""musical""|""the greatest showman""|""greatest showman""|""Michael Gracey""|""P.T. Barnum""|""Barnum and Bailey""|""Barnum Circus""|""Barnum and Bailey Circus""|""20th century fox""|""greatest showman trailer""|""trailer""|""official trailer""|""the greatest showman trailer""|""logan""|""Benj Pasek""|""Justin Paul"""',
                                                                                                                                                                                                                                                                                                        'vox.com|"vox""|""explain""|""shift change""|""future of work""|""automation""|""robots""|""jobs""|""technological unemployment""|""joss fong""|""heidi shierholz""|""martin ford""|""rise of the robots""|""humans""|""workers""|""employment""|""economics""|""macroeconomics""|""silicon valley""|""basic income"""',
 ...
                                                                                                                                                                                     'amrit maan new song|"amrit maan songs"|"amrit maan difference"|"difference by amrit maan"|"difference"|"amrit maan"|"ikwinder singh"|"daimond"|"gurnam bhullar"|"guru randhawa"|"mankirt aulakh"|"dj flow"|"latest punjabi songs"|"latest punjabi songs 2018"|"new punjabi song"|"punjabi songs"|"new songs 2018"|"avex dhillon"|"sidhu moose wala"|"trending nakhra"|"bamb beats"|"parada"|"parada jass manak"|"parada song full video"',
                                                                                                     'espn|"espn live"|"boston celtics"|"kyrie irving"|"kyrie"|"irving"|"kyrie irving celtics"|"kyrie irving lebron james"|"lebron james kyrie irving"|"lebron james celtics"|"lebron james kyrie irving celtics"|"kyrie lebron"|"first take"|"espn first"|"first take today"|"first take daily"|"first take live"|"stephen a. smith"|"stephen a smith"|"stephen a."|"stephen a"|"max kellerman"|"max"|"stephen"|"smith"|"first take espn"|"espn first take"|"first take stephen a smith"|"discussion"|"debate"|"morning show"',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'matrix|"action"|"action comedy"|"funny"|"best moments"|"best video games"|"video games"|"gaming"|"best gaming"|"airsoft"|"scene"|"comedy"',
                                                                                                        'Korean kpop reaction|"dkdktv"|"Kpop reaction"|"Korean reaction"|"bts"|"bts 5th anniversary"|"bts reaction"|"koreans bts"|"bts koreans react"|"koreans react to bts"|"what koreans think of bts"|"what do koreans think of"|"what do koreans think of bts"|"fake love"|"bts fake love"|"fake love reaction"|"bts billboard"|"bts billboard hot200"|"bts billboard winning"|"bts social award"|"bts award"|"how popular is bts"|"bts ARMY"|"bts success"|"bts tear"|"RM"|"kpop interview"|"asian boss"|"asian boss bts"',
                                                                                          'Hawaii volcano update|"Hawaii volcano"|"United States"|"America"|"United States of America"|"Images"|"video"|"The latest"|"us military"|"Fox News"|"sky news"|"al jazeera"|"bbc"|"cnn"|"voa"|"voa news"|"Hawaii"|"Volcano"|"Kilauea Volcano"|"Kilauea"|"Eruption"|"Hawaii volcano eruption"|"breaking news"|"latest news"|"business"|"finance"|"politics"|"local news"|"commentary"|"reports"|"current affairs"|"top news"|"headlines"|"news today"|"hawaii"|"united states"|"north america"|"Update"|"latest update"|"letest news"',
                                                                                                                                                          'australian|"blogger"|"vlogger"|"blog"|"vlog"|"guru"|"girl"|"review"|"try"|"on"|"chit"|"chat"|"get"|"ready"|"with"|"me"|"female"|"makeup"|"cosmetics"|"beauty"|"make"|"up"|"make-up"|"products"|"tutorial"|"how"|"to"|"how-to"|"DIY"|"video"|"application"|"caramorello"|"chloe"|"morello"|"chloemorello"|"aussie"|"eid"|"eid mubarak"|"eid 2018"|"eid makeup"|"eid makeup 2018"|"hijabi makeup"|"hijab makeup"|"hijab tutorial"|"bronze makeup"|"bronze eid makeup"',
                                                                     'wild|"minecraft ocelot"|"ocelot minecraft"|"adventure"|"adventurous"|"animals"|"breaking trail"|"coyote"|"coyote peterson"|"peterson"|"trail"|"Wild cat"|"predator cat"|"wildife"|"leopard"|"animals attack"|"ocelots"|"ferocious cat"|"ferocious beast"|"predator"|"meat eater"|"safari"|"rhino"|"african safari"|"kruger park"|"kruger national park"|"elephant"|"lion king"|"lions"|"rhinoceros"|"white rhinos"|"black rhino"|"impala"|"safari adventure"|"ulitmate safari adventure"|"kariega game reserve"|"kariega"|"ultimate safari"|"wildebeest"',
                                                                                                                                                                                                                                                                                                                                                         'annoying orange|"funny"|"fruit"|"talking"|"animation"|"daneboe"|"The Annoying Orange"|"how2"|"cartoon"|"comedy"|"satire"|"parody"|"spoof"|"lampoon"|"silly"|"how2 how to solve a mystery"|"how solve a mystery"|"mystery"|"horror"|"suspense"|"pear annoying orange"',
                                                                              '180612__TB02SorryExcuse|"News"|"Politics"|"The Young Turks"|"Ana Kasparian"|"Brett Erlich"|"Mark Thompson"|"TYT"|"progressive"|"liberal"|"justin trudeau"|"peter navarro"|"trudeau"|"donald trump"|"navarro"|"canada"|"news"|"politics"|"pierre trudeau"|"trump"|"g7"|"trade"|"navarro savages justin trudeau"|"larry kudlow"|"white house"|"nafta"|"trade war"|"president trump"|"trudeau g7"|"trudeau vs trump"|"larry kudlow trudeau"|"trump trudeau"|"trump trade adviser navarro"|"roberto navarro"|"navarro apologize"|"trump vs trudeau"',
                                                                                                                                                                                                                                                               'å³å®—æ†²|"å³å§å„’"|"å°æ˜Žæ˜Ÿå¤§è·Ÿç­"|"Sandy"|"Jacky wu"|"æ†²å“¥"|"ä¸­å¤©ç¶œåˆå°"|"CH36"|"ä¸­å¤©é›»è¦–å°"|"æˆ‘æ„›å°æ˜Žæ˜Ÿå¤§è·Ÿç­"|"è—äºº"|"ä¾†è³“"|"æŽå¦ç‘¾"|"çŽ‰å…”"|"ç­å‚‘"|"LaLa"|"å°å„ª"|"å°‘å°‘"|"å°ˆå®¶"|"é™³ç­±å±"|"å¾‹å¸«"|"Wendy"|"å¿ƒç†å¸«"|"ç¾…å‹å¿—"|"ç¤¾æœƒè¨˜è€…"|"æš´åŠ›"|"ç”·å‹"|"å¥³å‹"|"ç›¸è™•"|"ææ€–æƒ…äºº"|"æƒ…æ®º"']
Length: 50239, dtype: str
--------------------------------------------------
Column Name : views
Number of unique values : 132549
All unique values : [ 748374 2418783 3191434 ...  103339  773347  107392]
--------------------------------------------------
Column Name : likes
Number of unique values : 60628
All unique values : [ 57527  97185 146033 ... 321798  36481  25900]
--------------------------------------------------
Column Name : dislikes
Number of unique values : 14459
All unique values : [ 2966  6146  5339 ... 14650 10303 14006]
--------------------------------------------------
Column Name : comment_count
Number of unique values : 22317
All unique values : [15954 12703  8181 ... 21731 20213 20453]
--------------------------------------------------
Column Name : comments_disabled
Number of unique values : 2
All unique values : [False  True]
--------------------------------------------------
Column Name : ratings_disabled
Number of unique values : 2
All unique values : [False  True]
--------------------------------------------------
Column Name : video_error_or_removed
Number of unique values : 2
All unique values : [False  True]
--------------------------------------------------

#### Summary from the observations

- Columns with correct types:
index, video_id, title, channel_title, category_id, time_frame, published_day_of_week, publish_country, tags, views, likes, dislikes, comment_count, comments_disabled, ratings_disabled, video_error_or_removed are mostly fine.

- Columns needing conversions/cleaning:
trending_date, publish_date (stored as str instead of datetime).

- Columns with potential anomalies / considerations:
  - trending_date – unusual format DD.MM.YY which may require parsing.
  - publish_date – inconsistent formats (e.g., 13/11/2017, 31/12/2012) and older dates.
  - tags – contains very long strings, multiple entries separated by |, may require cleaning for analysis.
  - views, likes, dislikes, comment_count – large numeric ranges, check for outliers or zeros if needed.
  - publish_country – only 4 countries, may need standardization.